# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- feature/*

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*test/*.csproj'
    arguments: '--logger trx --configuration $(buildConfiguration) --collect "Code coverage"'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'cmx.hour-tracker-to-excel.web'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'cmx.hour-tracker-to-excel.web'
    customCommand: 'run build'
